pdb_mongodb:
  image: 'pdb_mongodb:1.0.0'
  environment:
    - MONGODB_ADMIN_USER=pdbroot
    - MONGODB_ADMIN_PASS=pdbroot1234
    - MONGODB_APPLICATION_DATABASE=pdbdb
    - MONGODB_APPLICATION_USER=pdbuser
    - MONGODB_APPLICATION_PASS=pdbuser1234
  ports:
    - '5500:27017'
  privileged: true
  volumes:
    - '~/pdbenvironment/mongodb/data:/data/db'
  restart: always

pdb_playground_mongodb:
  image: 'pdb_mongodb:1.0.0'
  environment:
    - MONGODB_ADMIN_USER=pdbroot
    - MONGODB_ADMIN_PASS=pdbroot1234
    - MONGODB_APPLICATION_DATABASE=playground
    - MONGODB_APPLICATION_USER=pdbuser
    - MONGODB_APPLICATION_PASS=pdbuser1234
  ports:
    - '5503:27017'
  privileged: true
  volumes:
    - '~/pdbenvironment/playground/mongodb/data:/data/db'
  restart: always

pdb_app:
  image: 'my_pdb_app:1.0.0'
  ports:
    - '8000:8000'
  privileged: true
  links:
    - pdb_playground_mongodb
    - pdb_mongodb
  volumes:
    - '~/pdbworkspace/Playgroundb/app:/opt/python/current/app'
  command: /bin/bash -c "cd /opt/python/current/app/;invoke build --env api-development;python3 manage.py runserver 0.0.0.0:8000"

pdb_web:
  image: 'my_pdb_web:1.0.0'
  ports:
    - '3001:3000'
  privileged: true
  restart: always
