sbk_mongodb:
  image: 'pdb_mongodb:1.0.0'
  environment:
    - MONGODB_ADMIN_USER=pdbroot
    - MONGODB_ADMIN_PASS=pdbroot1234
    - MONGODB_APPLICATION_DATABASE=development
    - MONGODB_APPLICATION_USER=pdbuser
    - MONGODB_APPLICATION_PASS=pdbuser1234
  ports:
    - '5500:27017'
  privileged: true
  volumes:
    - '~/pdbenvironment/mongodb/data:/data/db'
  restart: always
